---
# vars file for kvm-vms
vm_root_password: "redhat"
kvm_guests:
  sensu-server:
    name: sensu-server01
    config: >
      --ram 4096 --vcpus 2 --os-variant rhel7
      --disk path={{ kvm_images_dir }}/sensu-server01.qcow2,device=disk,bus=virtio,format=qcow2
      --import --noautoconsole --vnc --autostart
      --bridge  br-{{ kvm_bridges.br_1.device }}
      --name sensu-server01
    nics:
      eth0: |
        cat <<EOF > /etc/sysconfig/network-scripts/ifcfg-eth0
        DEVICE="eth0"
        ONBOOT="yes"
        TYPE="Ethernet"
        PEERDNS="yes"
        IPV6INIT="no"
        IPADDR=10.122.155.100
        NETMASK=255.255.255.224
        GATEWAY=10.122.155.97
        DNS1=64.102.6.247
        DNS2=173.37.87.157
        EOF
  redis-server:
    name: redis-server01
    config: >
      --ram 4096 --vcpus 2 --os-variant rhel7
      --disk path={{ kvm_images_dir }}/redis-server01.qcow2,device=disk,bus=virtio,format=qcow2
      --import --noautoconsole --vnc --autostart
      --bridge  br-{{ kvm_bridges.br_1.device }}
      --name redis-server01
    nics:
      eth0: |
        cat <<EOF > /etc/sysconfig/network-scripts/ifcfg-eth0
        DEVICE="eth0"
        ONBOOT="yes"
        TYPE="Ethernet"
        PEERDNS="yes"
        IPV6INIT="no"
        IPADDR=192.0.2..101
        NETMASK=255.255.255.0
        GATEWAY=192.0.2.1
        DNS1=10.12.32.1
        DNS2=8.8.8.8

